---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: config-cloudflare-ddns
  namespace: cloudflare-ddns
spec:
  encryptedData:
    config.json: AgADzoWp+orL4xzm7ZizgCLnuJcx+AtPy+1Qe3oifXyiZWE+c0tE/W1kt7hx45d6XpkESBsB/rXrKgVhQX1Oa/utucqV4utuJbuLg3wdQCcftLYxoTxJRqCECB/p7gUnw5Y2sk84pSBAk9FfINi8xANeZCi3E/9+F5RbEyQ3chd1SPrvZW6hfVE/uU/5/uacsA7u+uCG2ZWWXru1gCbrq7BfKmp6xxQaP52MtXWHvbZcj3dqoKAVSrBQcry/nxtzwzzt9I6KQj4/0sp5KnRcLXfV2O8C/pRltQ4NXkYzuniThNzGYjmReWmSgNrKh3wZeb/ovIOrl1Wp8Fq/TiigFTZ7KG07LnSo66tiq9ge8/cC5RX1vG7IwAetmjs86lb13FhiSDwZ2BfwX0gnIz7KN5fQSprxuEOQa5q2MKP9XM/8pDdRgyWnVAaTH+3oejpmjULTsLBkQT5bbd60E6UrHflmVl4sAhnG70DvxDYvdW3My3JuysTcBkLrsw1EowkR+i7F/jbwm9f9fYt98XFwwx+uh/HuMxgYw5uQzodKLaEB9sq0gTCOAuDpqF7xTmqmetYa16b6XSq3rr8S3Qx5raSshswE940Elq7N+FgThJLCpL1T01we629XP+B8Blusw1Fxqx56eVExnzl62epUIh9U/EodrewxkvWx9XApVy6s13E3w4b2E3i6UndZDLNC5lDEUxoZsl6kxfdyYB2OSZ4vw5xQafrJ47vdInCQutf7CAO8ZetKZeji/P2NHYAblO35Lt6A82NOTSjSWAE8pHO7l6W3Sehoh/nfQrd+4LHbwMZxOez0I8xiO8Wf6S9GS1BwGM/zCQWcZIjq3CLKr4pU2EtqU7H5qBJzXplsoaYAssYL9YEJ1FuyWmZZIvOEArjqijHyH3zkoLyQN/4kYOyYA4yOArQapWrdmWAa426z0CUyAPjBXSjzEUxmx19uT70k+hSoq7Q+hEPBob8swj8ETuv9v2KjPGeqVxEkIA2SMAJzwhSn6aeEETURu8ib+F1obmfINEH5msud612nTSIz/kotYpq89CytM7rCWeAx21WylqrsIU6+TSrUEPNBp9sWArsJLNWOUHl3XxEwN+nyDnX3fp1a7vY6M0/05+WMJlY0TIx/G0wmEoLZw2sCn92NkqxvHUrioUxuw0xf6w6fyaa1oTlE+Nr8M9Fr8MzziG/1R2KuHpDO0X6Ahhamue4Z4gTzz3ZmIZrZVVdD/Gu6pWr8swB/hIyp/RK5P7RcsvDAM5ognfeXCCY2+2/lFv/MNbQcNJS4Q+7ZsE2lMYG71S2Miu8f/G59imzUWx84NXW73q3Z5j8F5Xc0nO8zYU0ByRqGvnR4NEwGPcetT7GF2arplQM3KpCrAL+Yx1xFTUc2QRAdFexsOtn9Ag0cNkrDzVdKZ3R6MunuoWwWSVE=
  template:
    metadata:
      name: config-cloudflare-ddns
      namespace: cloudflare-ddns
    type: Opaque
