apiVersion: v1
kind: ConfigMap
metadata:
  name: romm-config
  namespace: romm
data:
  config.yml: |
    # RomM configuration file
    # Only uncomment the lines you want to use/modify

    # exclude:
    #   platforms:
    #     - excluded_folder_a
    #   roms:
    #     single_file:
    #       extensions:
    #         - xml
    #         - txt

    system:
      platforms:
        gc: gcn

    # filesystem:
    #   roms_folder: 'roms'
    #   skip_hash_calculation: false
