apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-library
  namespace: romm
spec:
  storageClassName: longhorn-main
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 200Gi  

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-db
  namespace: romm
spec:
  storageClassName: longhorn-main
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
