apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctfd-db
  namespace: ctfd
spec:
  storageClassName: longhorn-main
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctfd-uploads
  namespace: ctfd
spec:
  storageClassName: longhorn-main
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctfd-redis
  namespace: ctfd
spec:
  storageClassName: longhorn-main
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 256Mi
