apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: freshrss
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aminoa/homelab.git
    targetRevision: main
    path: freshrss
  destination:
    server: https://kubernetes.default.svc
    namespace: freshrss
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
