apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-wiki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aminoa/homelab.git
    targetRevision: main
    path: homelab-wiki
  destination:
    server: https://kubernetes.default.svc
    namespace: homelab-wiki
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
